basePath: /
definitions:
  handlers.ClipMoneyParsingAccountRequest:
    properties:
      account_url:
        description: Account URL
        example: https://vk.ru/id41699827
        type: string
    type: object
  handlers.ClipMoneyParsingAccountResponse:
    properties:
      data:
        description: Parsed account data
        items:
          $ref: '#/definitions/models.ClipMoneyResultRow'
        type: array
      message:
        description: Response message
        example: success
        type: string
      success:
        description: Response success status
        example: true
        type: boolean
    type: object
  handlers.ClipMoneyParsingUrlRequest:
    properties:
      url:
        description: URL to parse
        example: https://www.youtube.com/shorts/2EMmfcZ_UuY
        type: string
    type: object
  handlers.ClipMoneyParsingUrlResponse:
    properties:
      data:
        allOf:
        - $ref: '#/definitions/models.ResultRowUrl'
        description: Parsed video data
      message:
        description: Response message
        example: URL parsed successfully
        type: string
      success:
        description: Operation success status
        example: true
        type: boolean
    type: object
  handlers.DownloadVideosRequest:
    properties:
      urls:
        description: Videos URL to download
        example:
        - '[''https://vk.com/clip-226676596_456242668'']'
        items:
          type: string
        type: array
    type: object
  handlers.DownloadVideosResponse:
    properties:
      message:
        description: Response message
        example: URL parsed successfully
        type: string
      success:
        description: Operation success status
        example: true
        type: boolean
    type: object
  models.ClipMoneyResultRow:
    properties:
      account_url:
        type: string
      comments:
        type: integer
      description:
        type: string
      er:
        type: string
      likes:
        type: integer
      parsing_date:
        type: string
      publish_date:
        type: string
      shares:
        type: integer
      url:
        type: string
      views:
        type: integer
      virality:
        type: string
    type: object
  models.ResultRowUrl:
    properties:
      advertiserName:
        description: имя рекламодателя, только для вк
        type: string
      comments:
        description: Комментарии
        format: int64
        type: integer
      description:
        description: Описание
        type: string
      er:
        description: ER (likes+shares+comments)/views*100
        type: string
      erID:
        description: айди рекламы, только для вк
        type: string
      inn:
        description: инн, только для вк
        type: string
      likes:
        description: Лайки
        format: int64
        type: integer
      ownerUrl:
        description: Ссылка на канал
        type: string
      parsingDate:
        description: Дата обновления
        type: string
      publishDate:
        description: Дата публикации
        type: string
      shares:
        description: Репосты
        format: int64
        type: integer
      url:
        description: Cсылка на видео
        type: string
      videoUrls:
        items:
          type: string
        type: array
      views:
        description: Охват факт
        format: int64
        type: integer
      virality:
        description: Виральность (shared/views)*100
        type: string
    type: object
host: hammerhead-app-xw9wl.ondigitalocean.app
info:
  contact:
    email: support@your-domain.com
    name: API Support
  description: This is a sample server for parsing social media videos.
  termsOfService: http://swagger.io/terms/
  title: Parser social media videos
  version: "1.0"
paths:
  /clip_money/parsing_account:
    post:
      consumes:
      - application/json
      description: Parses clips for youtube, vk account, videos for tiktok and reels
        for instagram
      parameters:
      - description: Account URL to parse
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handlers.ClipMoneyParsingAccountRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully parsed account
          schema:
            $ref: '#/definitions/handlers.ClipMoneyParsingAccountResponse'
        "400":
          description: Invalid request format or missing account_url
          schema:
            $ref: '#/definitions/handlers.ClipMoneyParsingAccountResponse'
        "405":
          description: Method not allowed
          schema:
            $ref: '#/definitions/handlers.ClipMoneyParsingAccountResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/handlers.ClipMoneyParsingAccountResponse'
      summary: Parses clips, reels, videos for an account
      tags:
      - ClipMoney
  /clip_money/parsing_url:
    post:
      consumes:
      - application/json
      description: Parse video from tiktok, clip from youtube,vk or reel from instagram
      parameters:
      - description: URL to parse
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handlers.ClipMoneyParsingUrlRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully parsed URL
          schema:
            $ref: '#/definitions/handlers.ClipMoneyParsingUrlResponse'
        "400":
          description: Invalid request format or missing URL
          schema:
            $ref: '#/definitions/handlers.ClipMoneyParsingUrlResponse'
        "405":
          description: Method not allowed
          schema:
            $ref: '#/definitions/handlers.ClipMoneyParsingUrlResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/handlers.ClipMoneyParsingUrlResponse'
      summary: Parse video by URL
      tags:
      - ClipMoney
  /download_videos:
    post:
      consumes:
      - application/json
      description: Download video vk
      parameters:
      - description: URL to parse
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handlers.DownloadVideosRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully parsed URL
          schema:
            $ref: '#/definitions/handlers.DownloadVideosResponse'
        "400":
          description: Invalid request format or missing URL
          schema:
            $ref: '#/definitions/handlers.DownloadVideosResponse'
        "405":
          description: Method not allowed
          schema:
            $ref: '#/definitions/handlers.DownloadVideosResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/handlers.DownloadVideosResponse'
      summary: Download video by URL
      tags:
      - download
  /download_videos_get:
    get:
      consumes:
      - application/json
      description: Download video vk
      parameters:
      - description: URL to parse
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handlers.DownloadVideosRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully parsed URL
          schema:
            $ref: '#/definitions/handlers.DownloadVideosResponse'
        "400":
          description: Invalid request format or missing URL
          schema:
            $ref: '#/definitions/handlers.DownloadVideosResponse'
        "405":
          description: Method not allowed
          schema:
            $ref: '#/definitions/handlers.DownloadVideosResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/handlers.DownloadVideosResponse'
      summary: Download video by URL
      tags:
      - download
swagger: "2.0"
